project:
  type: website
  render:
    - "*.qmd"
    - "!materials/*/exercises/"
  output-dir: docs

from: markdown+emoji

website:
  title: "Introdução ao Shiny - R"
  page-navigation: true
  navbar:
    background: light
    foreground: dark
    right:
      - icon: github
        href: https://github.com/lgsilvaesilva/shiny101/
        aria-label: GitHub
  sidebar:
    - title: "Materials"
      style: docked
      align: left
      contents:
          - section: "Intro: Simple Shiny"
            contents:
            - text: "1. Bem-vido ao Shiny World"
              href: materials/1-single-docs/1-welcome-to-quarto/index.qmd
  page-footer:
    right: "This page is built with {{< fa heart >}} and [Quarto](https://quarto.org/)."
    left: "&copy; 2024, Luís G. Silva e Silva"

format: 
  html:
    theme: [default, assets/custom.scss]
    toc: false
    